name: Testler ve Statik Analiz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        laravel: ['10.0', '11.0']
        dependency-version: [prefer-stable]
        exclude:
          - php: '8.2'
            laravel: '11.0'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: PHP ${{ matrix.php }} Kur
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, fileinfo
          coverage: none
          tools: composer:v2

      - name: Laravel Sürümünü Ayarla
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" --no-interaction --no-update

      - name: Bağımlılıkları Yükle
        run: |
          composer update --${{ matrix.dependency-version }} --no-interaction --no-progress

      - name: Unit ve Feature Testlerini Çalıştır
        run: vendor/bin/pest

  style:
    runs-on: ubuntu-latest
    name: Kod Stili Kontrolü (Pint)

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: PHP 8.3 Kur
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, fileinfo
          coverage: none
          tools: composer:v2

      - name: Bağımlılıkları Yükle
        run: |
          composer update --prefer-stable --no-interaction --no-progress

      - name: Laravel Pint Çalıştır
        run: vendor/bin/pint --test

  static-analysis:
    runs-on: ubuntu-latest
    name: Statik Analiz (PHPStan)

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: PHP 8.3 Kur
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, fileinfo
          coverage: none
          tools: composer:v2

      - name: Bağımlılıkları Yükle
        run: |
          composer update --prefer-stable --no-interaction --no-progress

      - name: PHPStan Çalıştır
        run: vendor/bin/phpstan analyse 